language: php

branches:
  only:
    - master
    - develop

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --dev

script: ./vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm